/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import CLASES.Michi;
import CONTROLADOR.Controlador_michi;





/**
 *
 * @author Administrador
 */
public class Menu_michi extends javax.swing.JInternalFrame {

    /**
     * Creates new form Op1
     */
    public Menu_michi() {
        initComponents();
        setLocation(500, 500);
        setSize(500, 500);
        
      
        
    }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));
        getContentPane().add(c1);
        getContentPane().add(c2);
        getContentPane().add(c3);
        getContentPane().add(c4);
        getContentPane().add(c5);
        getContentPane().add(c6);
        getContentPane().add(c7);
        getContentPane().add(c8);
        getContentPane().add(c9);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
           Michi modelo=new Michi(); 
           
           Controlador_michi cm=new Controlador_michi(this, modelo);
           cm.iniciar_vista();
            
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton c1;
    public javax.swing.JButton c2;
    public javax.swing.JButton c3;
    public javax.swing.JButton c4;
    public javax.swing.JButton c5;
    public javax.swing.JButton c6;
    public javax.swing.JButton c7;
    public javax.swing.JButton c8;
    public javax.swing.JButton c9;
    // End of variables declaration//GEN-END:variables
}
